---
- name: Compile and deploy Edge
  hosts: edge_node
  become: true

  # We setup the edge user outside of the role because otherwise things like Rust and Go installation may fail.
  pre_tasks:
    - name: Check if repo-specific secrets file exists
      delegate_to: localhost
      connection: local
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/vars/secrets.yml"
      register: repo_secrets_file
      become: false

    - name: If repo-specific secrets file exists, load it in
      delegate_to: localhost
      connection: local
      ansible.builtin.include_vars:
        file: "vars/secrets.yml"
      when: repo_secrets_file.stat.exists
      become: false

    - name: Install the acl package
      ansible.builtin.package:
        name: acl
        state: present

    - name: Create a group for Edge
      ansible.builtin.group:
        name: "{{ edge_system_group | default('edge') }}"
        gid: 1337
        system: true

    - name: Create a user for Edge
      ansible.builtin.user:
        name: "{{ edge_system_user | default('edge') }}"
        group: "{{ edge_system_group | default('edge') }}"
        home: "{{ edge_system_home | default('/var/lib/arg-edge') }}"
        shell: /bin/bash
        uid: 1337
        createhome: true
        system: true

  roles:
    # Install Golang using the Gantsign role.
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'
    # Install Rust using a lightly customised role.
    - role: zorlin.rust
      become_user: "{{ edge_system_user | default('edge') }}"
    # Compile and install edge, updating and restarting it if necessary.
    - role: arg-edge
